Edited fixtuer/contact. Stopped to get TypeError: modify_contact_by_index() missing 1 required positional argument: 'index'. Now I get AttributeError: 'NoneType' object has no attribute 'group'